### ISSUE TITLE
Add geom_barmekko() function and GeomBarMekko ggproto object

### ISSUE THREAD

**Issue by jrnold** [ryninho/mekko#1]
Hi, I talked to you after the BARUG last night.  After the presentation, I looked through your code and you could definitely write a `geom_barmekko` function that returns a geom and would allow you to use in facets, with groups, and all that goodness.

Take a look at the source for [geom_bar](https://github.com/tidyverse/ggplot2/blob/4d2ca992dc37fee598d83d3d3f524dbba38f4187/R/geom-bar.r). The function is just a wrapper to create and return a `ggproto` object for the geom. The heavy lifting is done by that object, and requires defining function to transform the data and calculate various things. https://ggplot2.tidyverse.org/articles/extending-ggplot2.html covers the internals of how ggplot works. Also [this help page](https://ggplot2.tidyverse.org/reference/ggplot2-ggproto.html) for the different types of ggproto objects (Geom, Stat, etc.) is useful.

The `ggproto` object could use `GeomBar` as a template and inherit from `GeomRect`. I think the only difference between `GeomBar` and `GeomBarMekko` would be to rewrite the `setup_data()` method to use `positions()` to calculate the widths and also calculate the correct `xmin` and `xmax` locations. Then remove `draw_panel()` since you don't need the "hack".

I've written a few geoms, so I'd be happy to answer any questions. I could also give it a go and open a PR.

**Comment by ryninho** [comment]
@jrnold sorry I just saw this. Give it a go! I remember trying to do it as a geom and failing but maybe I didn't understand ggproto enough at the time. It was during a hackathon and I had limited time.

**Comment by jrnold** [comment]
At the moment I'm crunched for time, but if you want to give it a go, I'd be happy to help. ggproto is pretty obtuse at first (but no more than `substitute`), but I found that tweaking some of the existing geoms works pretty well, even without understanding the entire pipeline of ggplot.

**Comment by jrnold** [comment]
I didn't get as far as I'd like on this but in my branch jrnold/mekko@5f02c63901a6165f961ab474165618bb64854ef0, I created a `GeomBarMekko` ggproto class and `geom_barmekko()` function. The problem is that the x-axis in them is the cumulative sum of the width variables. The fill aesthetic can be used to color the groups, and . I see why you did it as a function rather than a geom. The difficult part is setting up the x-axis scales to show the labels of the categories rather than the width variable values, and do that in a way that works across faceting. I'd need to dig more into ggplot2 internals: but there's an example of writing a custom facetter in a ggplot2 vignette, and the **ggalt** package has an axis geom that may provide some ideas.

I also had a go at converting `barmekko()` to use the new tidy eval system.
